### ISSUE TITLE
method mk.single_file bug (torrent length)

### ISSUE THREAD

**Issue by aeusse** [stewrutledge/makeTorrent#2]
There is a bug using the method mk.single_file (makeTorrent/makeTorrent.py). It adds twice the length of the source file. I think one solution could be removing line 138 (length += len(filedata)). Or the other one could be replacing "length = len(open(realPath).read())" by "length = 0" in line 128. Thank you for your attention.

**Comment by stewrutledge** [comment]
Looks like option two was the problem, as you can see the rest of the variables are initialized empty.

Thanks for the report, can you pull master and see if it's working as expected now?

**Comment by stewrutledge** [comment]
Pushed a new version to pypi, length seems to work as expected now with single file torrents.

**Comment by aeusse** [comment]
Hi. Sorry I couldn't test earlier. It is working like a charm. Also the new
answer with the info hash is correct. Both things were tested using
rtorrent. Thank you
