### ISSUE TITLE
Consider using OSI approved license?

### ISSUE THREAD

**Issue by legoktm** [stewrutledge/makeTorrent#5]
Hi, the current license has a "non commercial" clause in it, meaning it doesn't meet the Open Source Definition: https://opensource.org/definition. Would you be willing to relicense it under a OSI approved license?

**Comment by stewrutledge** [comment]
Interesting issue.

I've been meaning to go back to this repo recently and do some maintenance like writing tests and hopefully getting it up to Python 3. I guess I can take a look at the license too.

Is there a specific use case for this library that would necessitate that it allowed commercial use?

**Comment by stewrutledge** [comment]
Scratch that, I'll just move it over to an MIT license.

No reason not to.

**Comment by legoktm** [comment]
> Is there a specific use case for this library that would necessitate that it allowed commercial use?

I was investigating this library for use on [Wikimedia's Tool Labs](https://wikitech.wikimedia.org/wiki/Portal:Tool_Labs) platform, which requires all code to be under an OSI approved license.

**Comment by stewrutledge** [comment]
Cool! Like I said I'll get it moved over to an OSI approved license asap, probably tomorrow.

**Comment by stewrutledge** [comment]
By "tomorrow" I meant "more than four years later" :)

**Comment by legoktm** [comment]
Thank you! Still appreciated :)

You'll probably want to update the license= field in setup.py too.

**Comment by stewrutledge** [comment]
Good thought, done :)

Did you ever end up using this?
